# Base configs
baseurl: "https://arminnorouzi.github.io/sightsavorphotography"
#baseurl: "" # Comment the above line and uncomment this to test the website locally
image_fulls_loc: "/images/fulls"
image_thumbs_loc: "/images/thumbs"
google_analytics: ""

# UI configs
title: "Sight Savor Photography"
subtitle: "See the world through Sight Savor!"
author: "Sight Savor"
header:
  title: "Photography"
  subtitle: "by Sight Savor"
footer:
  name: "Hey there, my name is Ram"
  bio: "Sight Savor Photography, established by Armin and Sara, two tech-savvy enthusiasts with a flair for immortalizing the world's splendor, marries cutting-edge technology with the timeless art of photography. Armin, an engineering Ph.D. graduate and a Machine Learning Engineer, brings precision and a keen eye for detail, capturing moments with a creative edge. Sara, with her Master's in Software Engineering and experience at Google, adds her quick reflexes for capturing nature's spontaneous beauty. Together, they transform every shot into a tech-inspired visual story, teaching the art of seeing the world through a unique, technologically-enriched lens."
web_design: "AJ"
# Configure which exif data to display
# Tag is the actual exif tag, icon is a fontawesome icon. Use JSON notation without line breaks
exif: '[{"tag": "Model", "icon": "camera-retro"}, {"tag": "FNumber", "icon": "dot-circle-o"}, {"tag": "ExposureTime", "icon": "clock-o"}, {"tag": "ISOSpeedRatings", "icon": "info-circle"}]'
social_urls:
  instagram: "https://www.instagram.com/sightsavor"
