# Base configs
baseurl: "https://arminnorouzi.github.io/sightsavorphotography"
#baseurl: "" # Comment the above line and uncomment this to test the website locally
image_fulls_loc: "/images/fulls"
image_thumbs_loc: "/images/thumbs"
google_analytics: ""

# UI configs
title: "Photography by Sight Savor Photography"
subtitle: "See the world through Sight Savor!"
author: "Sight Savor"
header:
  title: "Photography"
  subtitle: "by Sight Savor Photography"
footer:
  name: "Hey there, my name is Ram"
  bio: "Sight Savor Photography, founded by two tech enthusiasts with a passion for capturing the world's beauty, blends innovative technology with the art of photography. Our expertise in tech infuses our work with a unique perspective, ensuring every shot is not just a picture, but a tech-inspired masterpiece. We're dedicated to savoring each moment, turning fleeting memories into lasting visuals."
web_design: "AJ"
# Configure which exif data to display
# Tag is the actual exif tag, icon is a fontawesome icon. Use JSON notation without line breaks
exif: '[{"tag": "Model", "icon": "camera-retro"}, {"tag": "FNumber", "icon": "dot-circle-o"}, {"tag": "ExposureTime", "icon": "clock-o"}, {"tag": "ISOSpeedRatings", "icon": "info-circle"}]'
social_urls:
  instagram: "https://www.instagram.com/ram_patra"
